---
- name: Run command to add opennebula pkg key
  ansible.builtin.command: wget -q -O- https://downloads.opennebula.org/repo/repo.key | apt-key add -
  become: yes
  ignore_errors: yes

- name: Add opennebula repo to the system
  ansible.builtin.command: echo "deb https://downloads.opennebula.org/repo/6.2/Ubuntu/20.04 stable opennebula" | sudo tee /etc/apt/sources.list.d/opennebula.list
  become: yes

- name: Install opennebula kvm
  become: yes
  apt:
    pkg:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virtinst
      - virt-manager
      - opennebula-node
    state: latest
    update_cache: true