---

- name: Ensure docker is in a running state
  service:
    name: docker
    state: started
  register: dockerDetails
  until: dockerDetails.status.ActiveState == "active"
  retries: 15
  delay: 20

# TODO: move this to a "network" role?
# other apps are dependent on this network, so it must run before
# any Docker command
- name: Create reverse-proxy Docker network
  community.docker.docker_network:
    name: reverse-proxy
    state: present

- name: Create app folder
  file:
    state: directory
    path: "{{ apps_path }}/reverse-proxy"

- name: Copy docker-compose file
  copy:
    src: docker-compose.yaml
    dest: "{{ apps_path }}/reverse-proxy/docker-compose.yaml"

- name: Run docker-compose file
  community.docker.docker_compose:
    project_src: "{{ apps_path }}/reverse-proxy/"
    state: present