---

- name: apply common configuration to all nodes
  hosts: all
  gather_facts: yes
  roles:
    - common
  tags: common

# - name: Install and configure the reverse-proxy
#   hosts: reverse-proxy
#   gather_facts: yes
#   roles:
#     - reverse-proxy
#   tags: reverse-proxy

- name: install and configure opennebula
  hosts: opennebula
  gather_facts: yes
  roles:
    - opennebula
  tags: opennebula
