---

- name: apply common configuration to all nodes
  hosts: all
  gather_facts: yes
  roles:
    - common
  tags: common

- name: install and configure opennebula
  hosts: opennebula
  gather_facts: yes
  roles:
    - opennebula
  tags: opennebula

- name: install and configure opennebula-node
  hosts: opennebula-node
  gather_facts: yes
  roles:
    - opennebula-node
  tags: opennebula-node

- name: Install and configure the forward proxy
  hosts: proxy-entry
  gather_facts: yes
  roles:
    - proxy-entry
  tags: proxy-entry

- name: Install and configure the forward proxy
  hosts: proxy-node
  gather_facts: yes
  roles:
    - proxy-node
  tags: proxy-node
